# 觀念：
Tensorflow程序設計核心是`計算圖`，可分為`建立計算圖`與`執行計算圖`兩種

## 建立 const

In [1]:
import tensorflow as tf
ts_c = tf.constant(2,name='ts_c')
ts_c

<tf.Tensor 'ts_c:0' shape=() dtype=int32>

## 建立 Variable

In [3]:
import warnings
warnings.filterwarnings('ignore')
ts_x = tf.Variable(ts_c+5,name='ts_x')
ts_x
#shape=() 零維的tensor，也就是數值

<tf.Variable 'ts_x_1:0' shape=() dtype=int32_ref>

## 建立Session執行Computational Graph

In [4]:
sess=tf.Session()
init = tf.global_variables_initializer() #初始化模型參數
sess.run(init)
print('ts_c=',sess.run(ts_c))

ts_c= 2


In [5]:
print('ts_x=',sess.run(ts_x))

ts_x= 7


In [6]:
print('ts_c=',ts_c.eval(session=sess))

ts_c= 2


In [7]:
print('ts_x=',ts_x.eval(session=sess))

ts_x= 7


In [8]:
sess.close()

## Session open close

In [9]:
import tensorflow as tf
ts_c = tf.constant(2,name='ts_c')
ts_x = tf.Variable(ts_c+5,name='ts_x')

sess=tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
print('ts_c=',sess.run(ts_c))
print('ts_x=',sess.run(ts_x))
sess.close()

ts_c= 2
ts_x= 7


## With語法開啟Session
### session有時候會忘記關閉，或執行發生異常導致沒關閉
### 離開with就自動關閉session

In [10]:
import tensorflow as tf
ts_c = tf.constant(2,name='ts_c')
ts_x = tf.Variable(ts_c+5,name='ts_x')
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('ts_c=',sess.run(ts_c))
    print('ts_x=',sess.run(ts_x))

ts_c= 2
ts_x= 7


## placeholder

In [11]:
#placeholder用來暫時儲存變量，傳輸數據sess.run(***, feed_dict={input: **})
width = tf.placeholder("int32")
height = tf.placeholder("int32")
area=tf.multiply(width,height)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=',sess.run(area,feed_dict={width: 6, height: 8}))

area= 48


## Create dim 1 tensor

In [12]:
ts_X = tf.Variable([0.4,0.2,0.4])
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X=sess.run(ts_X)
    print(X)

[0.4 0.2 0.4]


In [13]:
print(X.shape)

(3,)


## Create dim 2 tensor

In [14]:
ts_X = tf.Variable([[0.4,0.2,0.4]])
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X=sess.run(ts_X)
    print(X)   

[[0.4 0.2 0.4]]


In [15]:
print('shape:',X.shape)

shape: (1, 3)


In [16]:
W = tf.Variable([[-0.5,-0.2 ],[-0.3, 0.4 ],[-0.5, 0.2 ]])
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W_array=sess.run(W)
    print(W_array)

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]


In [17]:
print(W_array.shape)

(3, 2)


## matmul

In [18]:
X = tf.Variable([[1.,1.,1.]])
W = tf.Variable([[-0.5,-0.2 ],[-0.3, 0.4 ],[-0.5, 0.2 ]])
XW =tf.matmul(X,W)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XW ))

[[-1.3  0.4]]


## tf.add

In [19]:
b = tf.Variable([[ 0.1,0.2]])
XW =tf.Variable([[-1.3,0.4]])
Sum =XW+b
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('Sum:')
    print(sess.run(Sum ))

Sum:
[[-1.1999999  0.6      ]]


## Y=X*W+b

In [20]:
X = tf.Variable([[1.,1.,1.]])
W = tf.Variable([[-0.5,-0.2 ],[-0.3, 0.4 ],[-0.5, 0.2 ]])
b = tf.Variable([[0.1,0.2]])
XWb =tf.matmul(X,W)+b
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:')
    print(sess.run(XWb ))

XWb:
[[-1.1999999  0.6      ]]
